export const customColors: string[] = [
  'bg-[#E1F5FE]',
  'bg-[#F9D5DF]',
  'bg-[#F5F5DC]',
  'bg-[#F2E6D9]',
  'bg-[#F0E68C]',
  'bg-[#AFEEEE]',
  'bg-[#D3D3D3]',
  'bg-[#FFB6C1]',
  'bg-[#E0FFFF]',
  'bg-[#ADD8E6]',
  'bg-[#F7DC6F]',
  'bg-[#E1F5FE]',
  'bg-[#90EE90]',
];
